server:
  port: 3000
  basePath: "/hippo/api"
database:
  host: "127.0.0.1"
  port: 6033
  name: "hippo_db"
  
  # ENV Variables
  username: "root" 
  password: "DB_PASSWORD"

# Set path to firebase key
firebase:
  path: "../../hippo-3b249-firebase-adminsdk-jz8r8-cbeabdae53.json"