# Workflow to validate Go build, Go test, and Docker image build
name: Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      working-directory: ./server
      run: go build -v ./...

    - name: Test
      working-directory: ./server
      run: go test -v ./...

    - name: Build the Docker image
      working-directory: ./server
      run: docker build . --file Dockerfile --tag hippo-server:$(date +%s)
